version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./Backend/.env

  frontend:
    build:
      context: ./graph-frontend
    ports:
      - "8081:8081"
